### ISSUE TITLE
v2.2.1 cannot run

### ISSUE THREAD

**Issue by maxsky** [simonnilsson/ios-uploader#23]
direct run it will report this error

```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Cannot find module 'C:\snapshot\ios-uploader\node_modules\axios\dist\node\axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
    at resolveExports (internal/modules/cjs/loader.js:450:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\snapshot\\ios-uploader\\node_modules\\axios\\package.json',
  pkg: true
}
```

v2.2.0 no problem, it still can upload

**Comment by simonnilsson** [comment]
Hi, thanks for reporting the issue. Binary builds should be fixed in v2.2.2 
https://github.com/simonnilsson/ios-uploader/releases/tag/v2.2.2
